[package]
name = "yew-ui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
lib-tft-set5-wasm = { path = "../libs/tft-set5-wasm" }
serde =  { version = "1.0.130", features = ["derive"] }